admin_api:
    resource: "@AdminAPIBundle/Controller/"
    type:     annotation
    prefix:   /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_login_check:
    path: /api/login_check

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"