<?php

namespace Admin\APIBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassifiedAdvertisementImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedAdvertisementImageRepository extends EntityRepository
{
}
